apiVersion: v1
kind: Service
metadata:
  name: hello-python-service2
spec:
  selector:
    app: hello-python2
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python2
spec:
  selector:
    matchLabels:
      app: hello-python2
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python2
    spec:
      containers:
      - name: hello-python2
        image: rewreu/flask:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000